version: '3'

services:

  app:
    build:
      context: ./app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s ./entrypoint.sh
    container_name: app
    volumes:
      - ./app:/app
    networks:
      - net
    depends_on: 
       - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - net
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net

networks:
  net:
    driver: bridge